from PIL.Image import init, EXTENSION, OPEN, SAVE, PILLOW_VERSION
from datetime import date
from sys import argv

init()
accepted_exts = tuple((k.lower() for k,v in EXTENSION.items() if (v in OPEN and v in SAVE)))
print('# Autogenerated from PIL {0} on {1} using `{2}`'.format(PILLOW_VERSION, date.today(), argv[0]))
print('accepted_img_exts = {0}'.format(accepted_exts))
